var express= require('express');
var superagent = require('superagent');

var router = express.Router();
router.post('/isGZ',(req,res,next)=>{
    var data=req.body;
    superagent
        .get('https://api.weixin.qq.com/cgi-bin/user/info?access_token='+data.token+'&openid='+data.openid+'&lang=zh_CN ')
        .type('form')
        .accept('json')
        .set('X-API-Key', 'foobar')
        .set('Accept', 'application/json')
        .end(function(reqe,rese){
            if(rese.ok) {
                if(rese.body){
                    res.json(rese.body)
                }
            }else{
                res.json({msg:'请求异常',code:'911',text:rese.text})
            }

        });
})

module.exports = router;

var a={
    checkWaiting
        :
        "N",
    createTime
        :
        1505985876000,
    creator
        :
        "张艳艳",
    creatorCode
        :
        "2c905cc75e5b9f75015e5bb80f100018",
    delFalg
        :
        null,
    evalId
        :
        "2c905cc75ea2221f015ea2cf678c0023",
    evalNo
        :
        "ZYYDSZYY310000ZYY0032017092100002",
    factPartCode
        :
        "Z3322366",
    factPartName
        :
        "",
    fitBackFlag
        :
        "0",
    fitBackType
        :
        "",
    flag
        :
        "0",
    handAddpartFlag
        :
        "1",
    id
        :
        "2c905cc75ea3ae09015ea3bef2e4000c",
    incCode
        :
        "",
    jmPrice
        :
        null,
    jyItemId
        :
        "/",
    loc4sPrice
        :
        null,
    locMarketPrice
        :
        null,
    lossPrice
        :
        2,
    manageFee
        :
        0.04,
    manageFeePct
        :
        0.01,
    partBrandname
        :
        null,
    partGroupCode
        :
        "",
    partGroupName
        :
        "",
    partIsPt
        :
        null,
    partKeyId
        :
        null,
    partNum
        :
        2,
    partRemark
        :
        null,
    partRemart
        :
        "",
    partStandard
        :
        "车灯",
    partStandardCode
        :
        "",
    partSum
        :
        6.04,
    partType
        :
        null,
    price
        :
        0,
    priceCeiling
        :
        0,
    priceCeilingFlag
        :
        "0",
    priceCeilingType
        :
        "",
    priceFlag
        :
        "2",
    priceSource
        :
        "zyy310000",
    priceUpdatedType
        :
        "0",
    purchaseFlag
        :
        null,
    queryFeePrice
        :
        0,
    queryPrice
        :
        0,
    refPrice
        :
        0,
    remainsPrice
        :
        0,
    remark
        :
        "",
    repairShopPrice
        :
        0,
    schemeCode
        :
        "2",
    selfPayPrice
        :
        0,
    sellerAddress
        :
        null,
    sellerId
        :
        null,
    sellerLxr
        :
        null,
    sellerName
        :
        null,
    sellerPhone
        :
        null,
    sellerTelephone
        :
        null,
    serialNo
        :
        1,
    sys4sPrice
        :
        null,
    sysMarketPrice
        :
        null,
    systemCompCode
        :
        "402880f65b860b84015ea3bec3db059b",
    thirdPartyServiceFlag
        :
        "0",
}
